import { readFileSync } from 'fs'
import { test, expect } from 'bun:test'

test('MCP exposes the V1 room lifecycle and parent worker execution tools with room token fields', () => {
  const server = readFileSync('server.ts', 'utf8')

  expect(server).toContain("name: 'create_room_with_bot_invited'")
  expect(server).toContain("name: 'archive_room'")
  expect(server).toContain("name: 'bind_worker_room'")
  expect(server).toContain("name: 'start_worker_agent'")
  expect(server).toContain("name: 'send_worker_task'")
  expect(server).toContain("name: 'capture_worker_report'")
  expect(server).toContain("desired_room_name")
  expect(server).toContain("parent_chat_id")
  expect(server).toContain('bind a worker room cwd/runtime metadata from the current Orchestrator parent room')
  expect(server).toContain('start or resume the assigned worker agent in a bound worker room from the current Orchestrator parent room')
  expect(server).toContain('send a bounded Worker Task to a started/bound worker room from the current Orchestrator parent room')
  expect(server).toContain('retrieve worker-room transcript/reportback facts from the current Orchestrator parent room')
  expect(server).toContain('must match this call\\\'s ccm_room_token room')
  expect(server).toContain('do not use the desired/new worker room as chat_id')
  expect(server).toContain("ccm_room_token")
  expect(server).not.toContain("name: 'create_telegram_room'")
  expect(server).not.toContain("name: 'adopt_room'")
})

test('daemon room control routes are gated by token, adapter, and orchestrator flag', () => {
  const daemon = readFileSync('daemon.ts', 'utf8')

  expect(daemon).toContain('assertOrchestratorRoom(route.channelKey)')
  expect(daemon).toContain("case 'create_room_with_bot_invited'")
  expect(daemon).toContain("case 'archive_room'")
  expect(daemon).toContain("case 'bind_worker_room'")
  expect(daemon).toContain("case 'start_worker_agent'")
  expect(daemon).toContain("case 'send_worker_task'")
  expect(daemon).toContain("case 'capture_worker_report'")
  expect(daemon).toContain('adapter.createRoomWithBotInvited')
  expect(daemon).toContain('adapter.archiveRoom')
  expect(daemon).toContain('setRoom(workerCk, cwd, runtime)')
  expect(daemon).toContain('setRoomOrchestratorFlag(workerCk, false)')
  expect(daemon).toContain("if (!cwd.startsWith('/')) throw new Error('cwd must be absolute')")
  expect(daemon).toContain('startNew(workerCk, roomCwd(workerCk), runtime, true, true)')
  expect(daemon).toContain("if (!sessionId) throw new Error('worker agent must be started before sending a task')")
  expect(daemon).toContain('call start_worker_agent before send_worker_task')
  expect(daemon).toContain('deliverUserTurn(workerCk')
  expect(daemon).toContain('workerTranscriptFacts(workerCk, runtime, limit)')
  expect(daemon).toContain("lastAssistantMessage: [...entries].reverse().find(entry => entry.role !== 'user')?.text")
  expect(daemon).toContain('JSON.stringify(resultFacts)')
  expect(daemon).toContain('Room is not flagged as an Agent Control Path orchestrator room')
  expect(daemon).toContain('Room lifecycle operation is not supported by')
})
