import { readFileSync } from 'fs'
import { test, expect } from 'bun:test'
import { CCM_MCP_TOOLS } from '../mcp-tools.js'

test('MCP exposes the V1 room lifecycle and parent worker execution tools with bound-room routing', () => {
  const server = readFileSync('server.ts', 'utf8')
  const toolText = JSON.stringify(CCM_MCP_TOOLS)

  expect(server).toContain('tools: CCM_MCP_TOOLS')
  expect(toolText).toContain('create_room_with_bot_invited')
  expect(toolText).toContain('archive_room')
  expect(toolText).toContain('bind_worker_room')
  expect(toolText).toContain('start_worker_agent')
  expect(toolText).toContain('send_worker_task')
  expect(toolText).toContain('capture_worker_report')
  expect(toolText).toContain('desired_room_name')
  expect(toolText).toContain('parent_chat_id')
  expect(toolText).toContain('bind a worker room cwd/runtime metadata from the current Orchestrator parent room')
  expect(toolText).toContain('start or resume the assigned worker agent in a bound worker room from the current Orchestrator parent room')
  expect(toolText).toContain('send a bounded Worker Task to a started/bound worker room from the current Orchestrator parent room')
  expect(toolText).toContain('retrieve worker-room transcript/reportback facts from the current Orchestrator parent room')
  expect(toolText).toContain('do not use the desired/new worker room as chat_id')
  expect(server).not.toContain("ccm_room_token")
  expect(toolText).not.toContain('create_telegram_room')
  expect(toolText).not.toContain('adopt_room')
})

test('daemon room control routes are gated by bound room, adapter, and orchestrator flag', () => {
  const daemon = readFileSync('daemon.ts', 'utf8')

  expect(daemon).toContain('assertOrchestratorRoom(route.channelKey)')
  expect(daemon).toContain("case 'create_room_with_bot_invited'")
  expect(daemon).toContain("case 'archive_room'")
  expect(daemon).toContain("case 'bind_worker_room'")
  expect(daemon).toContain("case 'start_worker_agent'")
  expect(daemon).toContain("case 'send_worker_task'")
  expect(daemon).toContain("case 'capture_worker_report'")
  expect(daemon).toContain('adapter.createRoomWithBotInvited')
  expect(daemon).toContain('adapter.archiveRoom')
  expect(daemon).toContain('setRoom(workerCk, cwd, runtime)')
  expect(daemon).toContain('setRoomOrchestratorFlag(workerCk, false)')
  expect(daemon).toContain("if (!cwd.startsWith('/')) throw new Error('cwd must be absolute')")
  expect(daemon).toContain('startNew(workerCk, roomCwd(workerCk), runtime, true, true)')
  expect(daemon).toContain("if (!sessionId) throw new Error('worker agent must be started before sending a task')")
  expect(daemon).toContain('call start_worker_agent before send_worker_task')
  expect(daemon).toContain('deliverUserTurn(workerCk')
  expect(daemon).toContain('workerTranscriptFacts(workerCk, runtime, limit)')
  expect(daemon).toContain("lastAssistantMessage: [...entries].reverse().find(entry => entry.role !== 'user')?.text")
  expect(daemon).toContain('JSON.stringify(resultFacts)')
  expect(daemon).toContain('Room is not flagged as an Agent Control Path orchestrator room')
  expect(daemon).toContain('Room lifecycle operation is not supported by')
})
